project:
  type: website
  output-dir: docs

website:
  title: "Mitchell Lane"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: Research.qmd
        text: Projects
      - href: Education.qmd
        text: Education
      - href: CV.qmd
        text: CV

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

