project:
  type: website
  output-dir: docs

website:
  title: "Mitchell Lane"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



